#!/bin/bash
#
# Generates combined ai-prompt.md files for each platform
# Combines: shared/guidelines.md + optional shared platform infrastructure + {platform}/integrate.md
#
# Usage: ./script/generate-prompts.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_DIR="$SCRIPT_DIR/../docs"

# Platforms to generate prompts for
PLATFORMS=("android" "ios" "flutter" "unity" "react-native" "react-native-expo")

echo "Generating combined AI prompt files..."

for platform in "${PLATFORMS[@]}"; do
  PLATFORM_DIR="$DOCS_DIR/$platform"
  INTEGRATE_FILE="$PLATFORM_DIR/integrate.md"
  OUTPUT_FILE="$PLATFORM_DIR/ai-prompt.md"
  SHARED_SOURCE_FILES=("shared/guidelines.md")

  # Platforms that produce an iOS target need the same native NSE/App Group setup.
  # Expo is handled by onesignal-expo-plugin instead of the manual shared Xcode flow.
  case "$platform" in
    ios|flutter|unity|react-native)
      SHARED_SOURCE_FILES+=("shared/ios-push-infrastructure.md")
      ;;
  esac
  
  # Skip if platform directory or integrate.md doesn't exist
  if [[ ! -d "$PLATFORM_DIR" ]]; then
    echo "  Skipping $platform (directory not found)"
    continue
  fi
  
  if [[ ! -f "$INTEGRATE_FILE" ]]; then
    echo "  Skipping $platform (integrate.md not found)"
    continue
  fi
  
  echo "  Generating $platform/ai-prompt.md"
  
  # Create combined file with header
  cat > "$OUTPUT_FILE" << HEADER
<!--
  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
  
  This file is generated by: script/generate-prompts.sh
  Source files:
$(for source_file in "${SHARED_SOURCE_FILES[@]}"; do echo "    - $source_file"; done)
    - $platform/integrate.md
  
  To make changes, edit the source files and run the build script.
-->

HEADER

  # Append shared source files
  first_shared_file=true
  for source_file in "${SHARED_SOURCE_FILES[@]}"; do
    if [[ "$first_shared_file" == false ]]; then
      echo "" >> "$OUTPUT_FILE"
      echo "---" >> "$OUTPUT_FILE"
      echo "" >> "$OUTPUT_FILE"
    fi
    cat "$DOCS_DIR/$source_file" >> "$OUTPUT_FILE"
    first_shared_file=false
  done
  
  # Add separator
  echo "" >> "$OUTPUT_FILE"
  echo "---" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  
  # Append platform-specific content
  cat "$INTEGRATE_FILE" >> "$OUTPUT_FILE"
  
done

echo "Done!"
